# Generated by Django 3.2.12 on 2024-02-21 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import workers.inspectors.data_validate_inspector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, validators=[workers.inspectors.data_validate_inspector.check_str])),
                ('birth_date', models.DateField()),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, validators=[workers.inspectors.data_validate_inspector.check_str])),
                ('birth_date', models.DateField()),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[workers.inspectors.data_validate_inspector.check_str])),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateField(default=datetime.datetime(2024, 2, 21, 15, 50, 11, 250072, tzinfo=utc))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.employee')),
                ('product', models.ManyToManyField(to='workers.Product')),
            ],
            options={
                'ordering': ['date', 'price'],
            },
        ),
    ]
