# Generated by Django 3.2.12 on 2024-02-21 15:51

from django.db import migrations, models
import workers.inspectors.data_validate_inspector


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True, validators=[workers.inspectors.data_validate_inspector.check_date]),
        ),
    ]
