# Generated by Django 3.2.12 on 2024-02-21 18:39

from django.db import migrations, models
import workers.inspectors.data_validate_inspector


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateTimeField(auto_now=True, validators=[workers.inspectors.data_validate_inspector.check_date]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[workers.inspectors.data_validate_inspector.check_price]),
        ),
    ]
